name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run linting
      run: pnpm run lint

    - name: Run type checking
      run: pnpm run typecheck

    - name: Run tests (CI mode - skip live integration tests)
      run: pnpm run test:ci
      env:
        # Skip live integration tests in CI
        SKIP_INTEGRATION_TESTS: true
        MOCK_ONLY_TESTS: true
        # Provide dummy values for config validation
        NAVIDROME_URL: http://ci-dummy-server:4533
        NAVIDROME_USERNAME: ci-dummy-user
        NAVIDROME_PASSWORD: ci-dummy-password
        # Disable debug logging
        DEBUG: false

    - name: Build package
      run: pnpm run build

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build package
      run: pnpm run build

    - name: Run tests before publish (CI mode)
      run: pnpm run test:ci
      env:
        SKIP_INTEGRATION_TESTS: true
        MOCK_ONLY_TESTS: true
        NAVIDROME_URL: http://ci-dummy-server:4533
        NAVIDROME_USERNAME: ci-dummy-user
        NAVIDROME_PASSWORD: ci-dummy-password
        DEBUG: false

    - name: Publish to npm
      run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}